# Generated by Django 5.1.3 on 2024-11-18 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_create_conversion_request_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversion_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='conversion.conversionrequest')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
